spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/fast_food
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true